version: 2
updates:
  - package-ecosystem: npm
    directory: /lorewire-app
    schedule:
      interval: weekly
      day: monday
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /pipeline
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
