// Generated by `python -m pipeline.export_app` - do not edit by hand.
// Published stories from the CMS, overlaid onto the sample catalog.
export interface PublishedStoryWord {
  word: string;
  start: number;
  end: number;
}

export interface PublishedStory {
  id: string;
  title: string;
  cat: string;
  dur: string;
  year: number;
  syn: string;
  body: string;
  source_url?: string;
  heroImage?: string;
  heroImageLandscape?: string;
  images?: string[];
  audioUrl?: string;
  videoUrl?: string;
  alignment?: PublishedStoryWord[];
}

export const PUBLISHED: PublishedStory[] = [
  {
    "id": "envelope",
    "title": "AITA for invoicing my coworkers after the office gift fund went missing?",
    "cat": "Entitled",
    "dur": "2:00",
    "year": 2026,
    "syn": "I volunteered to collect cash for our boss's retirement gift. The envelope had about 800 dollars in it by Friday. Over a long weekend it vanished from my drawer",
    "body": "By Friday, the retirement gift fund was looking solid. About $800 in cash and checks had been handed over, all of it stuffed into an envelope the poster had taken charge of after volunteering to collect for the boss's sendoff. The plan was simple: gather the money, keep it tucked away, and buy the gift.\n\nThen came the long weekend.\n\nWhen Monday rolled around, the envelope was gone.\n\nThe poster had left it in a drawer, and over the break, it vanished. Not a single bill. Not the envelope. Just empty drawer, blank stares, and a growing office problem that landed squarely on the person who'd offered to manage it.\n\nThe poster tried to calm things down by telling everyone the money was \"somewhere safe.\" But that answer did not sit well with the two coworkers who had helped fund the gift and wanted a clear accounting of where the cash had gone. They asked for details. They asked for proof. They asked, in effect, where the retirement money had gone and what exactly was happening with it.\n\nThe response was not what they expected.\n\nInstead of a breakdown, the poster sent them an invoice for their share.\n\nThe message was clear enough: if they wanted answers, they were going to be treated like customers. The coworkers, unsurprisingly, were not amused. The office mood shifted fast. People who had been casually chatting before now wanted no part of the situation. Half the floor stopped speaking to the poster.\n\nWhat started as a simple favor, collecting money for a retirement gift, turned into a missing-envelope mystery, a vague assurance that the funds were \"somewhere safe,\" and then a billing dispute nobody saw coming. The cash was gone from the drawer, the coworkers wanted an accounting, and the invoice only made things worse.\n\nBy the end of it, the retirement gift fund was still missing, the workplace was divided, and the person who had volunteered to handle the money was left with a quiet office and a very loud problem.",
    "source_url": "https://www.reddit.com/r/AmItheAsshole/comments/example/",
    "heroImage": "https://storage.googleapis.com/aporia-unleash/envelope/hero.png",
    "heroImageLandscape": "https://storage.googleapis.com/aporia-unleash/envelope/hero-landscape.png",
    "images": [
      "https://storage.googleapis.com/aporia-unleash/envelope/scene-1.png",
      "https://storage.googleapis.com/aporia-unleash/envelope/scene-2.png",
      "https://storage.googleapis.com/aporia-unleash/envelope/scene-3.png"
    ],
    "audioUrl": "https://storage.googleapis.com/aporia-unleash/envelope/narration.mp3",
    "videoUrl": "https://storage.googleapis.com/aporia-unleash/envelope/video.mp4",
    "alignment": [
      {
        "word": "by",
        "start": 0.1,
        "end": 0.7
      },
      {
        "word": "Friday",
        "start": 0.7,
        "end": 0.9
      },
      {
        "word": "the",
        "start": 0.9,
        "end": 1.4
      },
      {
        "word": "office",
        "start": 1.4,
        "end": 2.1
      },
      {
        "word": "retirement",
        "start": 2.1,
        "end": 2.7
      },
      {
        "word": "gift",
        "start": 2.7,
        "end": 3.2
      },
      {
        "word": "fund",
        "start": 3.2,
        "end": 3.8
      },
      {
        "word": "was",
        "start": 3.8,
        "end": 4.1
      },
      {
        "word": "looking",
        "start": 4.1,
        "end": 4.5
      },
      {
        "word": "solid",
        "start": 4.5,
        "end": 5.2
      },
      {
        "word": "about",
        "start": 5.2,
        "end": 5.9
      },
      {
        "word": "800",
        "start": 5.9,
        "end": 6.9
      },
      {
        "word": "dollars",
        "start": 6.9,
        "end": 7.0
      },
      {
        "word": "in",
        "start": 7.0,
        "end": 7.4
      },
      {
        "word": "cash",
        "start": 7.4,
        "end": 7.7
      },
      {
        "word": "all",
        "start": 7.7,
        "end": 8.3
      },
      {
        "word": "tucked",
        "start": 8.3,
        "end": 8.9
      },
      {
        "word": "into",
        "start": 8.9,
        "end": 9.0
      },
      {
        "word": "an",
        "start": 9.0,
        "end": 9.3
      },
      {
        "word": "envelope",
        "start": 9.3,
        "end": 9.6
      },
      {
        "word": "and",
        "start": 9.6,
        "end": 10.1
      },
      {
        "word": "sitting",
        "start": 10.1,
        "end": 10.6
      },
      {
        "word": "in",
        "start": 10.6,
        "end": 10.8
      },
      {
        "word": "one",
        "start": 10.8,
        "end": 11.1
      },
      {
        "word": "employee's",
        "start": 11.1,
        "end": 12.0
      },
      {
        "word": "drawer",
        "start": 12.0,
        "end": 12.2
      },
      {
        "word": "they",
        "start": 12.2,
        "end": 12.8
      },
      {
        "word": "had",
        "start": 12.8,
        "end": 13.1
      },
      {
        "word": "volunteered",
        "start": 13.1,
        "end": 13.8
      },
      {
        "word": "to",
        "start": 13.8,
        "end": 13.9
      },
      {
        "word": "handle",
        "start": 13.9,
        "end": 14.2
      },
      {
        "word": "it",
        "start": 14.2,
        "end": 14.4
      },
      {
        "word": "the",
        "start": 14.4,
        "end": 15.2
      },
      {
        "word": "plan",
        "start": 15.2,
        "end": 15.5
      },
      {
        "word": "was",
        "start": 15.5,
        "end": 15.7
      },
      {
        "word": "simple",
        "start": 15.7,
        "end": 16.1
      },
      {
        "word": "enough",
        "start": 16.1,
        "end": 16.4
      },
      {
        "word": "collect",
        "start": 16.4,
        "end": 17.3
      },
      {
        "word": "cash",
        "start": 17.3,
        "end": 17.7
      },
      {
        "word": "from",
        "start": 17.7,
        "end": 17.9
      },
      {
        "word": "co-workers",
        "start": 17.9,
        "end": 18.6
      },
      {
        "word": "buy",
        "start": 18.6,
        "end": 19.4
      },
      {
        "word": "the",
        "start": 19.4,
        "end": 19.5
      },
      {
        "word": "boss",
        "start": 19.5,
        "end": 19.8
      },
      {
        "word": "a",
        "start": 19.8,
        "end": 20.3
      },
      {
        "word": "retirement",
        "start": 20.3,
        "end": 20.6
      },
      {
        "word": "gift",
        "start": 20.6,
        "end": 20.9
      },
      {
        "word": "and",
        "start": 20.9,
        "end": 21.5
      },
      {
        "word": "keep",
        "start": 21.5,
        "end": 21.8
      },
      {
        "word": "the",
        "start": 21.8,
        "end": 22.1
      },
      {
        "word": "money",
        "start": 22.1,
        "end": 22.2
      },
      {
        "word": "in",
        "start": 22.2,
        "end": 22.5
      },
      {
        "word": "one",
        "start": 22.5,
        "end": 22.8
      },
      {
        "word": "place",
        "start": 22.8,
        "end": 23.1
      },
      {
        "word": "until",
        "start": 23.1,
        "end": 23.6
      },
      {
        "word": "it",
        "start": 23.6,
        "end": 23.8
      },
      {
        "word": "was",
        "start": 23.8,
        "end": 24.0
      },
      {
        "word": "needed",
        "start": 24.0,
        "end": 24.2
      },
      {
        "word": "the",
        "start": 24.2,
        "end": 25.2
      },
      {
        "word": "narrator",
        "start": 25.2,
        "end": 25.8
      },
      {
        "word": "took",
        "start": 25.8,
        "end": 26.1
      },
      {
        "word": "the",
        "start": 26.1,
        "end": 26.2
      },
      {
        "word": "job",
        "start": 26.2,
        "end": 26.6
      },
      {
        "word": "gather",
        "start": 26.6,
        "end": 27.5
      },
      {
        "word": "the",
        "start": 27.5,
        "end": 27.6
      },
      {
        "word": "contributions",
        "start": 27.6,
        "end": 28.5
      },
      {
        "word": "and",
        "start": 28.5,
        "end": 29.0
      },
      {
        "word": "by",
        "start": 29.0,
        "end": 29.1
      },
      {
        "word": "the",
        "start": 29.1,
        "end": 29.3
      },
      {
        "word": "end",
        "start": 29.3,
        "end": 29.6
      },
      {
        "word": "of",
        "start": 29.6,
        "end": 29.6
      },
      {
        "word": "the",
        "start": 29.6,
        "end": 29.8
      },
      {
        "word": "week",
        "start": 29.8,
        "end": 30.1
      },
      {
        "word": "had",
        "start": 30.1,
        "end": 30.4
      },
      {
        "word": "the",
        "start": 30.4,
        "end": 30.5
      },
      {
        "word": "whole",
        "start": 30.5,
        "end": 30.9
      },
      {
        "word": "stack",
        "start": 30.9,
        "end": 31.4
      },
      {
        "word": "ready",
        "start": 31.4,
        "end": 31.7
      },
      {
        "word": "to",
        "start": 31.7,
        "end": 32.0
      },
      {
        "word": "go",
        "start": 32.0,
        "end": 32.1
      },
      {
        "word": "then",
        "start": 32.1,
        "end": 33.0
      },
      {
        "word": "came",
        "start": 33.0,
        "end": 33.5
      },
      {
        "word": "the",
        "start": 33.5,
        "end": 33.7
      },
      {
        "word": "long",
        "start": 33.7,
        "end": 34.0
      },
      {
        "word": "weekend",
        "start": 34.0,
        "end": 34.4
      },
      {
        "word": "when",
        "start": 34.4,
        "end": 35.1
      },
      {
        "word": "everyone",
        "start": 35.1,
        "end": 35.6
      },
      {
        "word": "returned",
        "start": 35.6,
        "end": 36.3
      },
      {
        "word": "the",
        "start": 36.3,
        "end": 36.6
      },
      {
        "word": "envelope",
        "start": 36.6,
        "end": 37.2
      },
      {
        "word": "was",
        "start": 37.2,
        "end": 37.5
      },
      {
        "word": "gone",
        "start": 37.5,
        "end": 38.0
      },
      {
        "word": "the",
        "start": 38.0,
        "end": 38.7
      },
      {
        "word": "narrator",
        "start": 38.7,
        "end": 39.3
      },
      {
        "word": "later",
        "start": 39.3,
        "end": 39.6
      },
      {
        "word": "said",
        "start": 39.6,
        "end": 40.1
      },
      {
        "word": "the",
        "start": 40.1,
        "end": 40.2
      },
      {
        "word": "money",
        "start": 40.2,
        "end": 40.5
      },
      {
        "word": "was",
        "start": 40.5,
        "end": 40.8
      },
      {
        "word": "somewhere",
        "start": 40.8,
        "end": 41.6
      },
      {
        "word": "safe",
        "start": 41.6,
        "end": 42.0
      },
      {
        "word": "which",
        "start": 42.0,
        "end": 42.7
      },
      {
        "word": "did",
        "start": 42.7,
        "end": 43.1
      },
      {
        "word": "not",
        "start": 43.1,
        "end": 43.3
      },
      {
        "word": "reassure",
        "start": 43.3,
        "end": 43.9
      },
      {
        "word": "anyone",
        "start": 43.9,
        "end": 44.4
      },
      {
        "word": "in",
        "start": 44.4,
        "end": 45.0
      },
      {
        "word": "fact",
        "start": 45.0,
        "end": 45.5
      },
      {
        "word": "the",
        "start": 45.5,
        "end": 45.9
      },
      {
        "word": "problem",
        "start": 45.9,
        "end": 46.3
      },
      {
        "word": "was",
        "start": 46.3,
        "end": 46.7
      },
      {
        "word": "exactly",
        "start": 46.7,
        "end": 47.2
      },
      {
        "word": "that",
        "start": 47.2,
        "end": 47.5
      },
      {
        "word": "it",
        "start": 47.5,
        "end": 48.2
      },
      {
        "word": "was",
        "start": 48.2,
        "end": 48.4
      },
      {
        "word": "not",
        "start": 48.4,
        "end": 48.8
      },
      {
        "word": "in",
        "start": 48.8,
        "end": 49.0
      },
      {
        "word": "the",
        "start": 49.0,
        "end": 49.1
      },
      {
        "word": "drawer",
        "start": 49.1,
        "end": 49.4
      },
      {
        "word": "not",
        "start": 49.4,
        "end": 50.1
      },
      {
        "word": "in",
        "start": 50.1,
        "end": 50.3
      },
      {
        "word": "the",
        "start": 50.3,
        "end": 50.4
      },
      {
        "word": "office",
        "start": 50.4,
        "end": 50.8
      },
      {
        "word": "and",
        "start": 50.8,
        "end": 51.5
      },
      {
        "word": "not",
        "start": 51.5,
        "end": 51.8
      },
      {
        "word": "in",
        "start": 51.8,
        "end": 52.0
      },
      {
        "word": "any",
        "start": 52.0,
        "end": 52.3
      },
      {
        "word": "place",
        "start": 52.3,
        "end": 52.8
      },
      {
        "word": "the",
        "start": 52.8,
        "end": 53.0
      },
      {
        "word": "rest",
        "start": 53.0,
        "end": 53.4
      },
      {
        "word": "of",
        "start": 53.4,
        "end": 53.4
      },
      {
        "word": "the",
        "start": 53.4,
        "end": 53.6
      },
      {
        "word": "team",
        "start": 53.6,
        "end": 53.8
      },
      {
        "word": "could",
        "start": 53.8,
        "end": 54.1
      },
      {
        "word": "find",
        "start": 54.1,
        "end": 54.4
      },
      {
        "word": "it",
        "start": 54.4,
        "end": 55.1
      },
      {
        "word": "was",
        "start": 55.1,
        "end": 55.3
      },
      {
        "word": "not",
        "start": 55.3,
        "end": 56.0
      },
      {
        "word": "in",
        "start": 56.0,
        "end": 56.5
      },
      {
        "word": "any",
        "start": 56.5,
        "end": 56.9
      },
      {
        "word": "sense",
        "start": 56.9,
        "end": 57.2
      },
      {
        "word": "as",
        "start": 58.3,
        "end": 58.6
      },
      {
        "word": "the",
        "start": 58.6,
        "end": 58.8
      },
      {
        "word": "story",
        "start": 58.8,
        "end": 59.3
      },
      {
        "word": "spread",
        "start": 59.3,
        "end": 59.6
      },
      {
        "word": "around",
        "start": 59.6,
        "end": 59.8
      },
      {
        "word": "the",
        "start": 59.8,
        "end": 59.9
      },
      {
        "word": "floor",
        "start": 59.9,
        "end": 60.2
      },
      {
        "word": "two",
        "start": 60.2,
        "end": 61.1
      },
      {
        "word": "co-workers",
        "start": 61.1,
        "end": 61.6
      },
      {
        "word": "asked",
        "start": 61.6,
        "end": 62.1
      },
      {
        "word": "for",
        "start": 62.1,
        "end": 62.3
      },
      {
        "word": "an",
        "start": 62.3,
        "end": 62.9
      },
      {
        "word": "accounting",
        "start": 62.9,
        "end": 63.1
      },
      {
        "word": "of",
        "start": 63.1,
        "end": 63.2
      },
      {
        "word": "the",
        "start": 63.2,
        "end": 63.3
      },
      {
        "word": "fund",
        "start": 63.3,
        "end": 63.7
      },
      {
        "word": "they",
        "start": 63.7,
        "end": 64.4
      },
      {
        "word": "wanted",
        "start": 64.4,
        "end": 64.7
      },
      {
        "word": "to",
        "start": 64.7,
        "end": 64.9
      },
      {
        "word": "know",
        "start": 64.9,
        "end": 65.1
      },
      {
        "word": "what",
        "start": 65.1,
        "end": 65.6
      },
      {
        "word": "had",
        "start": 65.6,
        "end": 65.9
      },
      {
        "word": "happened",
        "start": 65.9,
        "end": 66.1
      },
      {
        "word": "to",
        "start": 66.1,
        "end": 66.3
      },
      {
        "word": "the",
        "start": 66.3,
        "end": 66.4
      },
      {
        "word": "money",
        "start": 66.4,
        "end": 66.6
      },
      {
        "word": "they",
        "start": 66.6,
        "end": 66.8
      },
      {
        "word": "had",
        "start": 66.8,
        "end": 67.0
      },
      {
        "word": "put",
        "start": 67.0,
        "end": 67.2
      },
      {
        "word": "in",
        "start": 67.2,
        "end": 67.4
      },
      {
        "word": "and",
        "start": 67.4,
        "end": 68.0
      },
      {
        "word": "what",
        "start": 68.0,
        "end": 68.3
      },
      {
        "word": "the",
        "start": 68.3,
        "end": 68.4
      },
      {
        "word": "plan",
        "start": 68.4,
        "end": 68.9
      },
      {
        "word": "was",
        "start": 68.9,
        "end": 69.1
      },
      {
        "word": "now",
        "start": 69.1,
        "end": 69.6
      },
      {
        "word": "that",
        "start": 69.6,
        "end": 69.7
      },
      {
        "word": "the",
        "start": 69.7,
        "end": 69.9
      },
      {
        "word": "envelope",
        "start": 69.9,
        "end": 70.6
      },
      {
        "word": "had",
        "start": 70.6,
        "end": 71.0
      },
      {
        "word": "vanished",
        "start": 71.0,
        "end": 71.2
      },
      {
        "word": "instead",
        "start": 71.2,
        "end": 72.5
      },
      {
        "word": "of",
        "start": 72.5,
        "end": 72.5
      },
      {
        "word": "producing",
        "start": 72.5,
        "end": 73.1
      },
      {
        "word": "a",
        "start": 73.1,
        "end": 73.6
      },
      {
        "word": "neat",
        "start": 73.6,
        "end": 73.8
      },
      {
        "word": "breakdown",
        "start": 73.8,
        "end": 74.3
      },
      {
        "word": "the",
        "start": 74.3,
        "end": 74.9
      },
      {
        "word": "narrator",
        "start": 74.9,
        "end": 75.5
      },
      {
        "word": "sent",
        "start": 75.5,
        "end": 76.0
      },
      {
        "word": "them",
        "start": 76.0,
        "end": 76.2
      },
      {
        "word": "an",
        "start": 76.2,
        "end": 76.4
      },
      {
        "word": "invoice",
        "start": 76.4,
        "end": 77.0
      },
      {
        "word": "the",
        "start": 77.0,
        "end": 77.8
      },
      {
        "word": "invoice",
        "start": 77.8,
        "end": 78.4
      },
      {
        "word": "was",
        "start": 78.4,
        "end": 78.8
      },
      {
        "word": "for",
        "start": 78.8,
        "end": 79.2
      },
      {
        "word": "their",
        "start": 79.2,
        "end": 79.6
      },
      {
        "word": "share",
        "start": 79.6,
        "end": 80.2
      },
      {
        "word": "that",
        "start": 80.2,
        "end": 81.1
      },
      {
        "word": "move",
        "start": 81.1,
        "end": 81.5
      },
      {
        "word": "did",
        "start": 81.5,
        "end": 81.8
      },
      {
        "word": "not",
        "start": 81.8,
        "end": 82.2
      },
      {
        "word": "go",
        "start": 82.2,
        "end": 82.4
      },
      {
        "word": "over",
        "start": 82.4,
        "end": 82.6
      },
      {
        "word": "well",
        "start": 82.6,
        "end": 83.0
      },
      {
        "word": "what",
        "start": 83.0,
        "end": 83.6
      },
      {
        "word": "had",
        "start": 83.6,
        "end": 83.9
      },
      {
        "word": "started",
        "start": 83.9,
        "end": 84.4
      },
      {
        "word": "as",
        "start": 84.4,
        "end": 84.7
      },
      {
        "word": "a",
        "start": 84.7,
        "end": 84.8
      },
      {
        "word": "simple",
        "start": 84.8,
        "end": 85.3
      },
      {
        "word": "office",
        "start": 85.3,
        "end": 85.7
      },
      {
        "word": "collection",
        "start": 85.7,
        "end": 86.2
      },
      {
        "word": "turned",
        "start": 86.2,
        "end": 87.1
      },
      {
        "word": "into",
        "start": 87.1,
        "end": 87.4
      },
      {
        "word": "a",
        "start": 87.4,
        "end": 87.7
      },
      {
        "word": "quiet",
        "start": 87.7,
        "end": 88.3
      },
      {
        "word": "standoff",
        "start": 88.3,
        "end": 89.0
      },
      {
        "word": "after",
        "start": 89.0,
        "end": 89.9
      },
      {
        "word": "the",
        "start": 89.9,
        "end": 90.1
      },
      {
        "word": "invoice",
        "start": 90.1,
        "end": 90.7
      },
      {
        "word": "went",
        "start": 90.7,
        "end": 90.9
      },
      {
        "word": "out",
        "start": 90.9,
        "end": 91.1
      },
      {
        "word": "half",
        "start": 91.1,
        "end": 91.7
      },
      {
        "word": "the",
        "start": 91.7,
        "end": 91.9
      },
      {
        "word": "floor",
        "start": 91.9,
        "end": 92.4
      },
      {
        "word": "stopped",
        "start": 92.4,
        "end": 92.9
      },
      {
        "word": "speaking",
        "start": 92.9,
        "end": 93.4
      },
      {
        "word": "to",
        "start": 93.4,
        "end": 93.5
      },
      {
        "word": "the",
        "start": 93.5,
        "end": 93.7
      },
      {
        "word": "narrator",
        "start": 93.7,
        "end": 94.2
      },
      {
        "word": "the",
        "start": 94.2,
        "end": 94.9
      },
      {
        "word": "missing",
        "start": 94.9,
        "end": 95.3
      },
      {
        "word": "envelope",
        "start": 95.3,
        "end": 95.9
      },
      {
        "word": "was",
        "start": 95.9,
        "end": 96.3
      },
      {
        "word": "still",
        "start": 96.3,
        "end": 96.6
      },
      {
        "word": "missing",
        "start": 96.6,
        "end": 97.0
      },
      {
        "word": "the",
        "start": 97.0,
        "end": 97.6
      },
      {
        "word": "retirement",
        "start": 97.6,
        "end": 98.2
      },
      {
        "word": "gift",
        "start": 98.2,
        "end": 98.6
      },
      {
        "word": "was",
        "start": 98.6,
        "end": 98.9
      },
      {
        "word": "still",
        "start": 98.9,
        "end": 99.2
      },
      {
        "word": "unresolved",
        "start": 99.2,
        "end": 100.0
      },
      {
        "word": "and",
        "start": 100.0,
        "end": 100.6
      },
      {
        "word": "the",
        "start": 100.6,
        "end": 100.7
      },
      {
        "word": "people",
        "start": 100.7,
        "end": 101.1
      },
      {
        "word": "who",
        "start": 101.1,
        "end": 101.3
      },
      {
        "word": "had",
        "start": 101.3,
        "end": 101.5
      },
      {
        "word": "once",
        "start": 101.5,
        "end": 101.9
      },
      {
        "word": "handed",
        "start": 101.9,
        "end": 102.2
      },
      {
        "word": "over",
        "start": 102.2,
        "end": 102.4
      },
      {
        "word": "cash",
        "start": 102.4,
        "end": 103.0
      },
      {
        "word": "were",
        "start": 103.0,
        "end": 103.5
      },
      {
        "word": "now",
        "start": 103.5,
        "end": 103.7
      },
      {
        "word": "staring",
        "start": 103.7,
        "end": 104.4
      },
      {
        "word": "at",
        "start": 104.4,
        "end": 104.6
      },
      {
        "word": "a",
        "start": 104.6,
        "end": 104.7
      },
      {
        "word": "bill",
        "start": 104.7,
        "end": 105.1
      },
      {
        "word": "the",
        "start": 105.1,
        "end": 106.1
      },
      {
        "word": "narrator",
        "start": 106.1,
        "end": 106.6
      },
      {
        "word": "had",
        "start": 106.6,
        "end": 106.9
      },
      {
        "word": "volunteered",
        "start": 106.9,
        "end": 107.6
      },
      {
        "word": "to",
        "start": 107.6,
        "end": 107.8
      },
      {
        "word": "keep",
        "start": 107.8,
        "end": 108.1
      },
      {
        "word": "the",
        "start": 108.1,
        "end": 108.2
      },
      {
        "word": "fun",
        "start": 108.2,
        "end": 108.5
      },
      {
        "word": "together",
        "start": 108.5,
        "end": 108.8
      },
      {
        "word": "for",
        "start": 108.8,
        "end": 109.7
      },
      {
        "word": "a",
        "start": 109.7,
        "end": 109.7
      },
      {
        "word": "while",
        "start": 109.7,
        "end": 110.2
      },
      {
        "word": "that",
        "start": 110.2,
        "end": 110.7
      },
      {
        "word": "looked",
        "start": 110.7,
        "end": 111.0
      },
      {
        "word": "easy",
        "start": 111.0,
        "end": 111.3
      },
      {
        "word": "enough",
        "start": 111.3,
        "end": 111.6
      },
      {
        "word": "by",
        "start": 111.6,
        "end": 112.3
      },
      {
        "word": "Friday",
        "start": 112.3,
        "end": 112.8
      },
      {
        "word": "the",
        "start": 112.8,
        "end": 113.3
      },
      {
        "word": "envelope",
        "start": 113.3,
        "end": 113.9
      },
      {
        "word": "was",
        "start": 113.9,
        "end": 114.0
      },
      {
        "word": "full",
        "start": 114.0,
        "end": 114.3
      },
      {
        "word": "by",
        "start": 114.3,
        "end": 115.1
      },
      {
        "word": "Monday",
        "start": 115.1,
        "end": 115.5
      },
      {
        "word": "it",
        "start": 115.5,
        "end": 116.0
      },
      {
        "word": "was",
        "start": 116.0,
        "end": 116.2
      },
      {
        "word": "gone",
        "start": 116.2,
        "end": 116.5
      },
      {
        "word": "and",
        "start": 116.5,
        "end": 117.3
      },
      {
        "word": "after",
        "start": 117.3,
        "end": 117.6
      },
      {
        "word": "the",
        "start": 117.6,
        "end": 117.8
      },
      {
        "word": "questions",
        "start": 118.3,
        "end": 118.4
      },
      {
        "word": "started",
        "start": 118.4,
        "end": 118.7
      },
      {
        "word": "the",
        "start": 118.7,
        "end": 119.3
      },
      {
        "word": "response",
        "start": 119.3,
        "end": 119.9
      },
      {
        "word": "was",
        "start": 119.9,
        "end": 120.3
      },
      {
        "word": "not",
        "start": 120.3,
        "end": 120.7
      },
      {
        "word": "an",
        "start": 120.7,
        "end": 120.9
      },
      {
        "word": "explanation",
        "start": 120.9,
        "end": 121.5
      },
      {
        "word": "but",
        "start": 121.5,
        "end": 122.2
      },
      {
        "word": "an",
        "start": 122.2,
        "end": 122.6
      },
      {
        "word": "invoice",
        "start": 122.6,
        "end": 123.2
      }
    ]
  }
];
