// Generated by `python -m pipeline.export_app` - do not edit by hand.
// Published stories from the CMS, overlaid onto the sample catalog.
export interface PublishedStoryWord {
  word: string;
  start: number;
  end: number;
}

export interface PublishedStory {
  id: string;
  title: string;
  cat: string;
  dur: string;
  year: number;
  syn: string;
  body: string;
  heroImage?: string;
  images?: string[];
  audioUrl?: string;
  videoUrl?: string;
  alignment?: PublishedStoryWord[];
}

export const PUBLISHED: PublishedStory[] = [
  {
    "id": "envelope",
    "title": "AITA for invoicing my coworkers after the office gift fund went missing?",
    "cat": "Entitled",
    "dur": "2:00",
    "year": 2026,
    "syn": "I volunteered to collect cash for our boss's retirement gift. The envelope had about 800 dollars in it by Friday. Over a long weekend it vanished from my drawer",
    "body": "By Friday, the retirement gift fund was looking solid. About $800 in cash and checks had been handed over, all of it stuffed into an envelope the poster had taken charge of after volunteering to collect for the boss's sendoff. The plan was simple: gather the money, keep it tucked away, and buy the gift.\n\nThen came the long weekend.\n\nWhen Monday rolled around, the envelope was gone.\n\nThe poster had left it in a drawer, and over the break, it vanished. Not a single bill. Not the envelope. Just empty drawer, blank stares, and a growing office problem that landed squarely on the person who'd offered to manage it.\n\nThe poster tried to calm things down by telling everyone the money was \"somewhere safe.\" But that answer did not sit well with the two coworkers who had helped fund the gift and wanted a clear accounting of where the cash had gone. They asked for details. They asked for proof. They asked, in effect, where the retirement money had gone and what exactly was happening with it.\n\nThe response was not what they expected.\n\nInstead of a breakdown, the poster sent them an invoice for their share.\n\nThe message was clear enough: if they wanted answers, they were going to be treated like customers. The coworkers, unsurprisingly, were not amused. The office mood shifted fast. People who had been casually chatting before now wanted no part of the situation. Half the floor stopped speaking to the poster.\n\nWhat started as a simple favor, collecting money for a retirement gift, turned into a missing-envelope mystery, a vague assurance that the funds were \"somewhere safe,\" and then a billing dispute nobody saw coming. The cash was gone from the drawer, the coworkers wanted an accounting, and the invoice only made things worse.\n\nBy the end of it, the retirement gift fund was still missing, the workplace was divided, and the person who had volunteered to handle the money was left with a quiet office and a very loud problem.",
    "heroImage": "https://storage.googleapis.com/aporia-unleash/envelope/hero.png",
    "images": [
      "https://storage.googleapis.com/aporia-unleash/envelope/scene-1.png",
      "https://storage.googleapis.com/aporia-unleash/envelope/scene-2.png",
      "https://storage.googleapis.com/aporia-unleash/envelope/scene-3.png"
    ],
    "audioUrl": "https://storage.googleapis.com/aporia-unleash/envelope/narration.mp3",
    "videoUrl": "https://storage.googleapis.com/aporia-unleash/envelope/video.mp4",
    "alignment": []
  }
];
