// Generated by `python -m pipeline.export_app` - do not edit by hand.
// Published stories from the CMS, overlaid onto the sample catalog.
export interface PublishedStory {
  id: string;
  title: string;
  cat: string;
  dur: string;
  year: number;
  syn: string;
  body: string;
}

export const PUBLISHED: PublishedStory[] = [
  {
    "id": "envelope",
    "title": "AITA for invoicing my coworkers after the office gift fund went missing?",
    "cat": "Entitled",
    "dur": "2:00",
    "year": 2026,
    "syn": "I volunteered to collect cash for our boss's retirement gift. The envelope had about 800 dollars in it by Friday. Over a long weekend it vanished from my drawer",
    "body": "The office retirement gift started as one of those simple, cheerful tasks nobody wants but everybody appreciates: collect a little cash, buy the boss something nice, and call it a day. The narrator volunteered to handle it.\n\nBy Friday, the envelope was looking healthy. About $800 in cash had been collected for the boss's retirement gift, and the plan seemed set. Then came the long weekend.\n\nWhen everyone returned, the money was gone.\n\nThe envelope had been kept in the narrator's drawer, and somewhere between Friday and the office reopening, the cash vanished. The narrator told coworkers it was \"somewhere safe.\" It was not, in any sense, safe.\n\nAt first, there was confusion. Then there were questions. Two coworkers asked for an accounting of what had happened to the fund, wanting to know where the money had gone and how the gift was supposed to be handled now. Instead of a tidy explanation, they got an invoice.\n\nThe narrator sent the two coworkers a bill for their share of the missing amount.\n\nThat changed the tone of the whole floor.\n\nWhat had started as a volunteer gesture turned into a workplace standoff, with the missing envelope at the center of it. The narrator had collected the cash, stored it in a drawer over the long weekend, and come back to find it gone. But rather than absorb the loss or sort out the details calmly, the response to requests for an accounting was to invoice the people asking.\n\nThe reaction was immediate. Half the floor stopped speaking to the narrator.\n\nNow the office gift fund is no longer just about a retirement present. It's about the vanished envelope, the phrase \"somewhere safe,\" and the invoices that followed. The cash is still missing, the coworkers are still angry, and the narrator is left in the middle of an office that has gone quiet on one side of the floor."
  }
];
