// Pure-logic tests for the render_short dispatcher's helpers. The
// integration path (claim row → POST Cloud Run → mark done) is exercised
// by manual smoke against the live dispatcher; here we lock down only
// the parsing seam where bugs would silently break the hook-first splice.
//
// _plans/2026-06-28-hook-before-brand-intro.md.

import { describe, expect, it } from "vitest";
import {
  extractHookEndSecFromProps,
  stripHookFromProps,
  stripPosterTextFromProps,
} from "./route";

describe("extractHookEndSecFromProps", () => {
  it("returns hookEndSec in seconds when hook_end_ms is a positive number", () => {
    const props = { hook_end_ms: 2500, voiceover_url: "x.mp3" };
    const result = extractHookEndSecFromProps(props);
    expect(result.hookEndSec).toBe(2.5);
    expect(result.propsStripped).toBe(true);
    // Strip removes the key so Remotion never sees a phantom prop.
    expect("hook_end_ms" in props).toBe(false);
    // Everything else passes through untouched.
    expect(props.voiceover_url).toBe("x.mp3");
  });

  it("returns null when hook_end_ms is missing", () => {
    const props = { voiceover_url: "x.mp3" };
    const result = extractHookEndSecFromProps(props);
    expect(result.hookEndSec).toBeNull();
    expect(result.propsStripped).toBe(false);
  });

  it("returns null but still strips the key when hook_end_ms is malformed", () => {
    // Even invalid values get stripped so they can't pollute the
    // Remotion props. The splice just falls back to legacy ordering.
    for (const bad of [0, -100, NaN, Infinity, "2500", null, false]) {
      const props: Record<string, unknown> = { hook_end_ms: bad };
      const result = extractHookEndSecFromProps(props);
      expect(result.hookEndSec, `value=${JSON.stringify(bad)}`).toBeNull();
      expect(result.propsStripped, `value=${JSON.stringify(bad)}`).toBe(true);
      expect("hook_end_ms" in props).toBe(false);
    }
  });

  it("returns null when inputProps is not an object", () => {
    for (const bad of [null, undefined, 42, "props", []]) {
      const result = extractHookEndSecFromProps(bad);
      expect(result.hookEndSec, `value=${JSON.stringify(bad)}`).toBeNull();
      expect(result.propsStripped, `value=${JSON.stringify(bad)}`).toBe(false);
    }
  });

  it("does not mutate inputProps when hook_end_ms is absent", () => {
    const props = { voiceover_url: "x.mp3", end_hold_ms: 1500 };
    const before = JSON.stringify(props);
    extractHookEndSecFromProps(props);
    expect(JSON.stringify(props)).toBe(before);
  });
});

// _plans/2026-06-28-phase-2-social-poster-render.md (Part 0).
// The dispatcher strips the `hook` field from inputProps before they
// reach DoodleShort (which doesn't accept that prop). The poster
// renderer reads `hook` from `short_renders.props` via its own
// helper — never through the video render path.
describe("stripHookFromProps", () => {
  it("returns the hook string and strips the key when present", () => {
    const props = {
      hook: "Eight hundred dollars. Gone.",
      voiceover_url: "x.mp3",
    };
    const result = stripHookFromProps(props);
    expect(result.hook).toBe("Eight hundred dollars. Gone.");
    expect(result.propsStripped).toBe(true);
    expect("hook" in props).toBe(false);
    // Everything else passes through.
    expect(props.voiceover_url).toBe("x.mp3");
  });

  it("returns null when hook is missing", () => {
    const props = { voiceover_url: "x.mp3" };
    const result = stripHookFromProps(props);
    expect(result.hook).toBeNull();
    expect(result.propsStripped).toBe(false);
  });

  it("returns null but still strips the key when hook is empty / wrong type", () => {
    for (const bad of ["", 123, null, false, []]) {
      const props: Record<string, unknown> = { hook: bad };
      const result = stripHookFromProps(props);
      expect(result.hook, `value=${JSON.stringify(bad)}`).toBeNull();
      expect(result.propsStripped, `value=${JSON.stringify(bad)}`).toBe(true);
      expect("hook" in props).toBe(false);
    }
  });

  it("returns null when inputProps is not an object", () => {
    for (const bad of [null, undefined, 42, "props", []]) {
      const result = stripHookFromProps(bad);
      expect(result.hook, `value=${JSON.stringify(bad)}`).toBeNull();
      expect(result.propsStripped, `value=${JSON.stringify(bad)}`).toBe(false);
    }
  });

  it("does not mutate inputProps when hook is absent", () => {
    const props = { voiceover_url: "x.mp3", end_hold_ms: 1500 };
    const before = JSON.stringify(props);
    stripHookFromProps(props);
    expect(JSON.stringify(props)).toBe(before);
  });
});

// 2026-06-29 scope addition to
// _plans/2026-06-28-phase-2-social-poster-render.md. The dispatcher
// also strips `poster_text` (the climax-revealing line generated by
// the script LLM) from inputProps so DoodleShort doesn't see a phantom
// prop. The poster renderer reads `poster_text` directly from
// `short_renders.props`.
describe("stripPosterTextFromProps", () => {
  it("returns the poster_text and strips the key when present", () => {
    const props = {
      poster_text: "She refused. He emptied their joint account by morning.",
      voiceover_url: "x.mp3",
    };
    const result = stripPosterTextFromProps(props);
    expect(result.posterText).toBe(
      "She refused. He emptied their joint account by morning.",
    );
    expect(result.propsStripped).toBe(true);
    expect("poster_text" in props).toBe(false);
    expect(props.voiceover_url).toBe("x.mp3");
  });

  it("returns null when poster_text is missing (legacy story)", () => {
    const props = { voiceover_url: "x.mp3" };
    const result = stripPosterTextFromProps(props);
    expect(result.posterText).toBeNull();
    expect(result.propsStripped).toBe(false);
  });

  it("returns null but still strips when poster_text is empty / wrong type", () => {
    for (const bad of ["", 123, null, false, []]) {
      const props: Record<string, unknown> = { poster_text: bad };
      const result = stripPosterTextFromProps(props);
      expect(result.posterText, `value=${JSON.stringify(bad)}`).toBeNull();
      expect(result.propsStripped, `value=${JSON.stringify(bad)}`).toBe(true);
      expect("poster_text" in props).toBe(false);
    }
  });

  it("returns null when inputProps is not an object", () => {
    for (const bad of [null, undefined, 42, "props", []]) {
      const result = stripPosterTextFromProps(bad);
      expect(result.posterText, `value=${JSON.stringify(bad)}`).toBeNull();
      expect(result.propsStripped, `value=${JSON.stringify(bad)}`).toBe(false);
    }
  });

  it("does not mutate inputProps when poster_text is absent", () => {
    const props = { voiceover_url: "x.mp3", hook: "Eight hundred dollars. Gone." };
    const before = JSON.stringify(props);
    stripPosterTextFromProps(props);
    expect(JSON.stringify(props)).toBe(before);
  });
});
