"""Export PUBLISHED stories from the store into the Next app as a typed module.

The public site reads a static catalog, so publishing in the admin is a two-step
bridge: set a story to "published", then run this to push it into the app and
redeploy. Works against both backends — SQLite locally, Postgres in production
when `DATABASE_URL` is set.

    python -m pipeline.export_app

Only status='published' rows are exported, so unpublishing removes a story from
the next build.
"""
from __future__ import annotations

import json
from pathlib import Path

from pipeline import store

OUT = Path(__file__).resolve().parent.parent / "lorewire-app" / "src" / "data" / "published.ts"


def _year(row: dict) -> int:
    ts = row.get("published_at") or row.get("created_at") or ""
    try:
        return int(str(ts)[:4])
    except (ValueError, TypeError):
        return 2026


def _parse_json_col(raw, default):
    """JSON columns are stored as TEXT for cross-engine portability; an empty
    string and None both mean 'unset' here."""
    if not raw:
        return default
    try:
        return json.loads(raw)
    except (ValueError, TypeError):
        return default


def _bust(url: str | None, version: str) -> str | None:
    """Append `?v=<version>` to a media URL so a browser hit fetches the
    re-uploaded bytes rather than the cached copy at the same URL. GCS
    re-uploads at the same key don't change the URL, but we DO change
    `stories.updated_at` on every backfill, so threading that as `version`
    makes one updated_at per asset URL — and every refresh after a backfill
    gets the new image."""
    if not url:
        return url
    sep = "&" if "?" in url else "?"
    return f"{url}{sep}v={version}"


def main() -> None:
    rows = store.published_stories()
    # source_url isn't in published_stories' SELECT yet — pull it per row via
    # fetch_story(). Tiny cost: one extra query per published row, and there
    # are rarely more than a few dozen at a time.
    for r in rows:
        full = store.fetch_story(r["id"])
        if full and full.get("source_url"):
            r["source_url"] = full["source_url"]
        # Cache-bust signature derived from updated_at so a single GCS
        # re-upload (same URL, new bytes) gets a fresh query string.
        ts = (r.get("updated_at") or r.get("published_at") or "")
        v = ts[:19].replace(":", "").replace("-", "").replace("T", "")
        for k in ("hero_image", "hero_image_landscape", "audio_url", "video_url"):
            if r.get(k):
                r[k] = _bust(r[k], v)
        # `images` is a JSON-encoded list of URLs; deserialize, bust, re-encode.
        if r.get("images"):
            try:
                imgs = json.loads(r["images"]) if isinstance(r["images"], str) else r["images"]
                r["images"] = json.dumps([_bust(u, v) for u in imgs])
            except (ValueError, TypeError):
                pass
    data = [
        {
            "id": r["id"],
            "title": r["title"] or r["id"],
            "cat": r["category"] or "Drama",
            # Empty string when the pipeline never populated `stories.duration`
            # (most shorts today — the auto-apply path only swaps video_url).
            # The web side reads through loadLiveCatalog which backfills from
            # short_renders.props.duration_ms; the published.ts overlay no
            # longer carries the legacy "2:00" long-form fallback.
            "dur": r["duration"] or "",
            "year": _year(r),
            "syn": r["summary"] or "",
            "body": r["body"],
            # Media columns are emitted only when set so the JS-side check
            # `if (story.heroImage)` is honest about availability instead of
            # always-truthy with empty strings.
            **({"source_url": r["source_url"]} if r.get("source_url") else {}),
            **({"heroImage": r["hero_image"]} if r["hero_image"] else {}),
            **({"heroImageLandscape": r["hero_image_landscape"]} if r.get("hero_image_landscape") else {}),
            **({"heroHasBakedTitle": bool(r["hero_has_baked_title"])} if r.get("hero_has_baked_title") else {}),
            **({"images": _parse_json_col(r["images"], [])} if r["images"] else {}),
            **({"audioUrl": r["audio_url"]} if r["audio_url"] else {}),
            **({"videoUrl": r["video_url"]} if r["video_url"] else {}),
            **({"alignment": _parse_json_col(r["alignment"], [])} if r["alignment"] else {}),
        }
        for r in rows
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    ts = (
        "// Generated by `python -m pipeline.export_app` - do not edit by hand.\n"
        "// Published stories from the CMS, overlaid onto the sample catalog.\n"
        "export interface PublishedStoryWord {\n"
        "  word: string;\n"
        "  start: number;\n"
        "  end: number;\n"
        "}\n\n"
        "export interface PublishedStory {\n"
        "  id: string;\n"
        "  title: string;\n"
        "  cat: string;\n"
        "  dur: string;\n"
        "  year: number;\n"
        "  syn: string;\n"
        "  body: string;\n"
        "  source_url?: string;\n"
        "  heroImage?: string;\n"
        "  heroImageLandscape?: string;\n"
        "  heroHasBakedTitle?: boolean;\n"
        "  images?: string[];\n"
        "  audioUrl?: string;\n"
        "  videoUrl?: string;\n"
        "  alignment?: PublishedStoryWord[];\n"
        "}\n\n"
        "export const PUBLISHED: PublishedStory[] = "
        + json.dumps(data, ensure_ascii=True, indent=2)
        + ";\n"
    )
    OUT.write_text(ts, encoding="utf-8")
    print(f"wrote {len(data)} published stor(ies) to {OUT}")
    for d in data:
        media_bits = [k for k in ("heroImage", "images", "audioUrl", "videoUrl", "alignment") if k in d]
        suffix = f" + media: {', '.join(media_bits)}" if media_bits else ""
        print(f"  - {d['id']} ({len(d['body'])} chars){suffix}")


if __name__ == "__main__":
    main()
