"""Export PUBLISHED stories from the store into the Next app as a typed module.

The live site reads a static catalog, so publishing in the admin is a two-step
bridge until a production Postgres is connected: set a story to "published",
then run this to push it into the app and redeploy.

    python -m pipeline.export_app

Only status='published' rows are exported, so unpublishing removes a story from
the next build.
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from pipeline.config import DB_PATH

OUT = Path(__file__).resolve().parent.parent / "lorewire-app" / "src" / "data" / "published.ts"


def _year(row: sqlite3.Row) -> int:
    ts = row["published_at"] or row["created_at"] or ""
    try:
        return int(str(ts)[:4])
    except (ValueError, TypeError):
        return 2026


def _parse_json_col(raw, default):
    """JSON columns are stored as TEXT for cross-engine portability; an empty
    string and None both mean 'unset' here."""
    if not raw:
        return default
    try:
        return json.loads(raw)
    except (ValueError, TypeError):
        return default


def main() -> None:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT id, title, category, summary, body, duration, published_at, created_at, "
        "hero_image, images, audio_url, video_url, alignment "
        "FROM stories WHERE status='published' AND body IS NOT NULL AND body != '' "
        "ORDER BY published_at DESC"
    ).fetchall()
    data = [
        {
            "id": r["id"],
            "title": r["title"] or r["id"],
            "cat": r["category"] or "Drama",
            "dur": r["duration"] or "2:00",
            "year": _year(r),
            "syn": r["summary"] or "",
            "body": r["body"],
            # Media columns are emitted only when set so the JS-side check
            # `if (story.heroImage)` is honest about availability instead of
            # always-truthy with empty strings.
            **({"heroImage": r["hero_image"]} if r["hero_image"] else {}),
            **({"images": _parse_json_col(r["images"], [])} if r["images"] else {}),
            **({"audioUrl": r["audio_url"]} if r["audio_url"] else {}),
            **({"videoUrl": r["video_url"]} if r["video_url"] else {}),
            **({"alignment": _parse_json_col(r["alignment"], [])} if r["alignment"] else {}),
        }
        for r in rows
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    ts = (
        "// Generated by `python -m pipeline.export_app` - do not edit by hand.\n"
        "// Published stories from the CMS, overlaid onto the sample catalog.\n"
        "export interface PublishedStoryWord {\n"
        "  word: string;\n"
        "  start: number;\n"
        "  end: number;\n"
        "}\n\n"
        "export interface PublishedStory {\n"
        "  id: string;\n"
        "  title: string;\n"
        "  cat: string;\n"
        "  dur: string;\n"
        "  year: number;\n"
        "  syn: string;\n"
        "  body: string;\n"
        "  heroImage?: string;\n"
        "  images?: string[];\n"
        "  audioUrl?: string;\n"
        "  videoUrl?: string;\n"
        "  alignment?: PublishedStoryWord[];\n"
        "}\n\n"
        "export const PUBLISHED: PublishedStory[] = "
        + json.dumps(data, ensure_ascii=True, indent=2)
        + ";\n"
    )
    OUT.write_text(ts, encoding="utf-8")
    print(f"wrote {len(data)} published stor(ies) to {OUT}")
    for d in data:
        media_bits = [k for k in ("heroImage", "images", "audioUrl", "videoUrl", "alignment") if k in d]
        suffix = f" + media: {', '.join(media_bits)}" if media_bits else ""
        print(f"  - {d['id']} ({len(d['body'])} chars){suffix}")


if __name__ == "__main__":
    main()
