"""Regenerate `pipeline/mp3_silence.py` — the embedded silence buffers the
hook-first two-clip splice inserts between the hook and rest narration clips.

One blob per TTS provider MP3 format (see FORMATS below). Each blob is a bare
MPEG frame stream: encoded with the local ffmpeg, then run through
`voice.strip_mp3_container_tags` so no ID3/Xing noise ever reaches the byte
concat. Embedding the bytes as base64 in a Python module (instead of shipping
.mp3 asset files) guarantees the Vercel drain bundle always has them — module
imports can't be dropped by a bundler the way loose data files can.

Runs on a dev machine only (needs ffmpeg on PATH). CI never runs this; the
generated module is committed. Re-run when a TTS provider changes its MP3
format and add the new format tuple below.

Usage::

    python -m pipeline.scripts.gen_mp3_silence

Per _plans/2026-07-02-hook-clip-measured-boundary.md.
"""
from __future__ import annotations

import base64
import subprocess
import tempfile
from pathlib import Path

from pipeline import voice

# Target silence length. The splice cuts at buffer midpoint, so every known
# imprecision (frame-math vs decoded timeline ~40-80ms, AAC re-encode ~21ms,
# video frame ~33ms) must fit inside HALF of this with margin.
SILENCE_MS = 300

# (name, sample_rate, channels, bitrate) — one entry per provider MP3 format.
#   - Google TTS (every tier we expose) outputs 24 kHz mono MPEG-2 Layer III.
#   - ElevenLabs outputs 44.1 kHz MPEG-1 Layer III; channel count is read from
#     the real stream at runtime, so both mono and stereo variants ship.
FORMATS = [
    ("google_24k_mono", 24000, 1, "32k"),
    ("eleven_44k1_mono", 44100, 1, "128k"),
    ("eleven_44k1_stereo", 44100, 2, "128k"),
]

MODULE_PATH = Path(__file__).resolve().parent.parent / "mp3_silence.py"

HEADER = '''"""Embedded MP3 silence buffers for the hook-first two-clip splice.

GENERATED by `python -m pipeline.scripts.gen_mp3_silence` — do not edit the
blobs by hand. Each blob is ~{silence_ms}ms of encoded silence as a bare MPEG
frame stream (ID3/Xing stripped), keyed by the stream params of the clips it
may be spliced between. `silence_mp3_for` returns None on an unknown format so
the caller can fall back to a bufferless concat and log it.

Per _plans/2026-07-02-hook-clip-measured-boundary.md.
"""
from __future__ import annotations

import base64

# Nominal buffer length (the frame-exact value comes from counting the blob).
SILENCE_MS = {silence_ms}

# Keyed by (version, layer, sample_rate, channels) — the same fields
# `voice.mp3_stream_params` reports for a clip.
_SILENCE_B64: dict[tuple[str, int, int, int], str] = {{
{entries}}}


def silence_mp3_for(params: dict | None) -> bytes | None:
    """Silence blob matching a clip's `voice.mp3_stream_params`, or None."""
    if not params:
        return None
    key = (
        params.get("version"),
        params.get("layer"),
        params.get("sample_rate"),
        params.get("channels"),
    )
    blob = _SILENCE_B64.get(key)
    return base64.b64decode(blob) if blob else None
'''


def main() -> None:
    entries: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, rate, channels, bitrate in FORMATS:
            out = Path(tmp) / f"{name}.mp3"
            subprocess.run(
                [
                    "ffmpeg", "-y", "-loglevel", "error",
                    "-f", "lavfi", "-i", f"anullsrc=r={rate}:cl={'mono' if channels == 1 else 'stereo'}",
                    "-t", f"{SILENCE_MS / 1000:.3f}",
                    "-ar", str(rate), "-ac", str(channels),
                    "-c:a", "libmp3lame", "-b:a", bitrate,
                    str(out),
                ],
                check=True,
            )
            stripped = voice.strip_mp3_container_tags(out.read_bytes())
            params = voice.mp3_stream_params(stripped)
            if params is None:
                raise RuntimeError(f"{name}: stripped blob has no parseable frame")
            duration = voice.mp3_duration_ms(stripped)
            key = (params["version"], params["layer"], params["sample_rate"], params["channels"])
            print(f"[gen_mp3_silence] {name}: key={key} bytes={len(stripped)} duration={duration}ms")
            b64 = base64.b64encode(stripped).decode("ascii")
            wrapped = "\n".join(
                f'        "{b64[i:i + 76]}"' for i in range(0, len(b64), 76)
            )
            entries.append(f"    {key!r}:\n{wrapped},\n")
    MODULE_PATH.write_text(
        HEADER.format(silence_ms=SILENCE_MS, entries="".join(entries)),
        encoding="utf-8",
    )
    print(f"[gen_mp3_silence] wrote {MODULE_PATH}")


if __name__ == "__main__":
    main()
